# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf1231101a481a38f45a454db98ae3be2db593cac559e67f4647c6861263712ea09a0cc096c60b2ef8da019501301a33ef68542b15320f97e7785623d5992f06

test:
  secret_key_base: 20bcb0bc13a0e86492e29bbf291274f5a982ff732d9e194955ad5c707d3b040816f47eedbb53a5968dc8355fd95509fd135c1a942eba35fa8b59ddb671200709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
